swagger: "2.0"
info:
  version: "1.0.1"
  title: Hackathon app!

host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hack:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_hackathon
    get:
      description: Does the needful
      operationId: hack

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HackResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/BorkedHackResponse"
  /babble:
    x-swagger-router-controller: hello_hackathon
    get:
      description: It's almost like my grandma's neighbor
      operationId: babble

      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HackResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/BorkedHackResponse"
   
# complex objects have schema definitions
definitions:
  HackResponse:
    required:
      - message
    properties:
      message:
        type: string
  BorkedHackResponse:
    required:
      - message
    properties:
      message:
        type: string
